export const sourceAssetDirectory =
  "Beautice - Clinic & Beauty Consultation Website Design (Community)";

export const assetFiles = Object.freeze({
  references: {
    composite: "Beautice - Clinic & Beauty Consultation Website Design (Community).png",
    homeOne: "Home 1.png",
    homeTwo: "Home 2.png",
  },
  brand: {
    headerLogoSvg: "Main Logo.svg",
    headerLogoPng: "Main Logo.png",
    footerLogoSvg: "Footer Logo.svg",
    footerLogoPng: "Footer Logo.png",
  },
  backgrounds: [
    "Background Bubble.png",
    "Background Bubble-1.png",
    "Background Bubble-2.png",
    "Background Bubble-3.png",
    "Background Wave.png",
    "Bubble BG.png",
    "Bubble BG-1.png",
    "Bubble BG-2.png",
    "Bubble BG Footer.png",
    "Element Background.png",
    "Footer BG.png",
    "Footer BG-1.png",
    "Footer BG-2.png",
    "Footer BG 1.png",
    "Footer BG 2.png",
    "Footer BG 2-1.png",
    "Bottom BG.png",
    "Bottom BG-1.png",
    "BG-Elements.png",
    "Wave Line.png",
    "Wave Line-1.png",
  ],
  illustrations: [
    "Illustration-1.svg",
    "Illustration-1.png",
    "Illustration-2.png",
    "Animation1.png",
    "Animation1-1.png",
    "Animation2.png",
    "Animation2-1.png",
    "Animation3.png",
    "Animation3-1.png",
    "Contact Animations.png",
    "Contact Animations-1.png",
  ],
  serviceIcons: [
    "doctor 1.png",
    "handshake 1.png",
    "earth 1.png",
    "brotherhood 1.png",
    "icon-2.png",
  ],
  socialIcons: [
    "Facebook.png",
    "facebook-f.png",
    "Instagram.png",
    "linkedin-in.png",
    "Twitter.png",
    "youtube.png",
  ],
  controls: [
    "Play_button.png",
    "Polygon Play.png",
    "Polygon 1.png",
    "Polygon 1-1.png",
    "ToTop Button.png",
  ],
  partners: ["LOGO1.png", "LOGO2.png", "LOGO3.png", "LOGO4.png", "LOGO5.png"],
  inventory: {
    generatedManifest: "reference/manifests/assets.generated.json",
    note: "The generated manifest is authoritative for the complete file list, dimensions, hashes and duplicate groups.",
  },
});
