export const designTokens = Object.freeze({
  metadata: {
    source: "PNG reference exports from the Beautice Community design",
    status: "provisional-until-verified-per-section",
    referenceWidth: 1440,
  },
  color: {
    brandNavy: "#091156",
    brandPink: "#FF64AE",
    textBody: "#8B8B8B",
    textOnDark: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceMuted: "#F6F7FF",
    borderSoft: "#D9DDFE",
    footerNavy: "#0D165C",
    focus: "#2F5BFF",
  },
  typography: {
    fontFamily: '"Poppins", Arial, sans-serif',
    weight: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    size: {
      bodySmall: 14,
      body: 16,
      bodyLarge: 18,
      headingSmall: 24,
      headingMedium: 36,
      headingLarge: 48,
    },
    lineHeight: {
      compact: 1.25,
      heading: 1.35,
      body: 1.5,
      relaxed: 1.75,
    },
  },
  layout: {
    referenceWidth: 1440,
    contentMaxWidth: 1140,
    pageGutterDesktop: 32,
    pageGutterTablet: 24,
    pageGutterMobile: 20,
  },
  breakpoint: {
    small: 640,
    medium: 768,
    large: 1024,
    extraLarge: 1280,
    reference: 1440,
  },
  radius: {
    small: 8,
    medium: 15,
    large: 25,
    card: 42,
    pill: 999,
  },
  shadow: {
    card: "0 25px 50px 0 rgba(246, 247, 255, 1)",
    button: "0 17px 22px 0 rgba(255, 100, 174, 0.25)",
  },
});
